print("---------------------------------------------")
print("               HELLO APP")
print("---------------------------------------------")
print()
input_name = input("What is your name? ")
print("Hello " + input_name + "!!!")
